spring:
  datasource:
    druid:
      url: jdbc:mysql://47.96.150.17/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: q.123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    host: 47.96.150.17
    port: 6379
    password: q.123456


mybatis:
  configuration:
    cache-enabled: true
  type-aliases-package: pers.ycy.blog.common.domain
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    pers.ycy.blog.mapper: debug
  file: log/log.log
server:
  port: 7778